const test=require('node:test');const assert=require('node:assert/strict');const lib=require('../scripts/board-archive-lib');

test('parses real CATS data attributes and ignores other meetings',()=>{const html=`<table><tr><td class="result-name">Richland Bean Blossom School Board 8/18</td><td class="result-date">Tue, August 18, 2026</td><td><a data-m4v="M_RBB_260818.m4v" data-vtt="M_RBB_260818_subtitles.vtt" data-name="Richland Bean Blossom School Board 8/18" data-date="Tue, August 18, 2026" data-permalink="https://catstv.net/m.php?q=16312" href="#">View &gt;</a></td></tr><tr><td>Bloomington City Council</td><td><a data-permalink="https://catstv.net/m.php?q=1" href="#">View</a></td></tr></table>`;const rows=lib.parseCatsArchive(html);assert.equal(rows.length,1);assert.equal(rows[0].meetingDate,'2026-08-18');assert.equal(rows[0].sourceUrl,'https://catstv.net/m.php?q=16312');assert.equal(rows[0].captionUrl,'https://catstv.blob.core.windows.net/videoarchive/M_RBB_260818_subtitles.vtt');});

test('finds caption links and parses VTT timestamps',()=>{const html=`<video><track kind="captions" src="/captions/16312.vtt"></video>`;assert.deepEqual(lib.parseCaptionLinks(html,'https://catstv.net/m.php?q=16312'),['https://catstv.net/captions/16312.vtt']);const cues=lib.parseVtt(`WEBVTT\n\n00:01:02.500 --> 00:01:05.000\nSpecial education matters.\n\n01:02:03.100 --> 01:02:05.000\nSPED staffing update.`);assert.equal(cues.length,2);assert.equal(cues[0].timestampSeconds,62);assert.equal(cues[0].timestampLabel,'1:02');assert.equal(cues[1].timestampLabel,'1:02:03');});

test('parses board document links and classifies official records',()=>{const html=`<h2>2026 Board Meetings</h2><p>August 18, 2026 - Regular Meeting - <a href="/docs/agenda.pdf">Agenda</a> - <a href="/docs/minutes.pdf">Minutes</a></p>`;const links=lib.parseBoardLinks(html);assert.equal(links.length,2);assert.equal(links[0].meetingDate,'2026-08-18');assert.equal(links[0].sourceType,'agenda');assert.equal(links[1].sourceType,'minutes');});

test('groups searchable records into stable year shards',()=>{assert.equal(lib.recordShardKey({meetingDate:'2026-08-18'}),'2026');assert.equal(lib.recordShardKey({meetingDate:'2019-01-02'}),'2019');assert.equal(lib.recordShardKey({meetingDate:null}),'undated');});
